package com.destructivemod.item;

import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import com.destructivemod.DestructiveMod;

public class ModItems {
    public static final Item TERRA_CRUSHER = new DestructiveToolItem(new Item.Settings().maxCount(1), 18, 3, 40, "dust");
    public static final Item MAGMA_MAUL = new DestructiveToolItem(new Item.Settings().maxCount(1), 22, 4, 50, "flame");
    public static final Item VOID_HAMMER = new DestructiveToolItem(new Item.Settings().maxCount(1), 28, 5, 60, "portal");
    public static final Item THUNDER_SMASHER = new DestructiveToolItem(new Item.Settings().maxCount(1), 24, 4, 45, "electric");
    public static final Item FROST_BREAKER = new DestructiveToolItem(new Item.Settings().maxCount(1), 20, 4, 45, "snow");
    public static final Item QUAKE_HAMMER = new DestructiveToolItem(new Item.Settings().maxCount(1), 30, 6, 70, "dust");
    public static final Item METEOR_MAUL = new DestructiveToolItem(new Item.Settings().maxCount(1), 35, 7, 80, "flame");
    public static final Item ABYSS_CRUSHER = new DestructiveToolItem(new Item.Settings().maxCount(1), 38, 7, 85, "portal");
    public static final Item SOLAR_SMASHER = new DestructiveToolItem(new Item.Settings().maxCount(1), 40, 8, 90, "flame");
    public static final Item CHAOS_HAMMER = new DestructiveToolItem(new Item.Settings().maxCount(1), 45, 9, 100, "portal");
    public static final Item ENDER_BREAKER = new DestructiveToolItem(new Item.Settings().maxCount(1), 26, 5, 55, "portal");
    public static final Item TITAN_HAMMER = new DestructiveToolItem(new Item.Settings().maxCount(1), 50, 10, 120, "dust");
    public static final Item CORE_DRILL = new DestructiveToolItem(new Item.Settings().maxCount(1), 12, 2, 10, "dust");
    public static final Item PLASMA_BORE = new DestructiveToolItem(new Item.Settings().maxCount(1), 16, 2, 8, "electric");
    public static final Item SEISMIC_DRILL = new DestructiveToolItem(new Item.Settings().maxCount(1), 14, 3, 15, "dust");
    public static final Item MAGMA_PIERCER = new DestructiveToolItem(new Item.Settings().maxCount(1), 20, 3, 12, "flame");
    public static final Item VOID_DRILL = new DestructiveToolItem(new Item.Settings().maxCount(1), 22, 3, 15, "portal");
    public static final Item QUANTUM_BORE = new DestructiveToolItem(new Item.Settings().maxCount(1), 28, 4, 10, "electric");
    public static final Item TECTONIC_DRILL = new DestructiveToolItem(new Item.Settings().maxCount(1), 30, 4, 20, "dust");
    public static final Item NEUTRON_PIERCER = new DestructiveToolItem(new Item.Settings().maxCount(1), 35, 5, 8, "electric");
    public static final Item NOVA_BOMB = new DestructiveToolItem(new Item.Settings().maxCount(1), 30, 6, 60, "flame");
    public static final Item ANTIMATTER_CHARGE = new DestructiveToolItem(new Item.Settings().maxCount(1), 60, 10, 120, "portal");
    public static final Item FUSION_GRENADE = new DestructiveToolItem(new Item.Settings().maxCount(1), 25, 5, 50, "flame");
    public static final Item DARK_MATTER_MINE = new DestructiveToolItem(new Item.Settings().maxCount(1), 35, 7, 70, "portal");
    public static final Item PLASMA_CLUSTER = new DestructiveToolItem(new Item.Settings().maxCount(1), 32, 6, 55, "electric");
    public static final Item GRAVITON_BOMB = new DestructiveToolItem(new Item.Settings().maxCount(1), 50, 9, 100, "portal");
    public static final Item SINGULARITY_CHARGE = new DestructiveToolItem(new Item.Settings().maxCount(1), 70, 12, 150, "portal");
    public static final Item HYPERNOVA_MINE = new DestructiveToolItem(new Item.Settings().maxCount(1), 80, 14, 180, "flame");
    public static final Item PHOTON_LANCE = new DestructiveToolItem(new Item.Settings().maxCount(1), 20, 1, 5, "electric");
    public static final Item GAMMA_BEAM = new DestructiveToolItem(new Item.Settings().maxCount(1), 28, 2, 8, "electric");
    public static final Item PLASMA_CUTTER = new DestructiveToolItem(new Item.Settings().maxCount(1), 18, 1, 3, "flame");
    public static final Item NEUTRON_RAY = new DestructiveToolItem(new Item.Settings().maxCount(1), 35, 2, 10, "electric");
    public static final Item VOID_BEAM = new DestructiveToolItem(new Item.Settings().maxCount(1), 40, 3, 15, "portal");
    public static final Item SOLAR_LANCE = new DestructiveToolItem(new Item.Settings().maxCount(1), 50, 3, 12, "flame");
    public static final Item WORLD_SPLITTER = new DestructiveToolItem(new Item.Settings().maxCount(1), 30, 3, 20, "dust");
    public static final Item DIMENSION_BLADE = new DestructiveToolItem(new Item.Settings().maxCount(1), 28, 3, 18, "portal");
    public static final Item REALITY_CLEAVER = new DestructiveToolItem(new Item.Settings().maxCount(1), 38, 4, 25, "portal");
    public static final Item VOID_EDGE = new DestructiveToolItem(new Item.Settings().maxCount(1), 26, 3, 20, "portal");
    public static final Item CHAOS_SABER = new DestructiveToolItem(new Item.Settings().maxCount(1), 36, 4, 22, "flame");
    public static final Item OBLIVION_KATANA = new DestructiveToolItem(new Item.Settings().maxCount(1), 45, 5, 30, "portal");
    public static final Item ENTROPY_BLADE = new DestructiveToolItem(new Item.Settings().maxCount(1), 34, 4, 20, "dust");
    public static final Item ANNIHILATION_SWORD = new DestructiveToolItem(new Item.Settings().maxCount(1), 50, 6, 35, "flame");
    public static final Item TITAN_FIST = new DestructiveToolItem(new Item.Settings().maxCount(1), 25, 4, 25, "dust");
    public static final Item SEISMIC_GAUNTLET = new DestructiveToolItem(new Item.Settings().maxCount(1), 20, 3, 20, "dust");
    public static final Item MAGMA_CLAW = new DestructiveToolItem(new Item.Settings().maxCount(1), 24, 3, 15, "flame");
    public static final Item GRAVITY_FIST = new DestructiveToolItem(new Item.Settings().maxCount(1), 35, 5, 30, "portal");
    public static final Item VOID_GRIP = new DestructiveToolItem(new Item.Settings().maxCount(1), 42, 6, 35, "portal");
    public static final Item APOCALYPSE_STAFF = new DestructiveToolItem(new Item.Settings().maxCount(1), 40, 7, 40, "flame");
    public static final Item DESTRUCTION_WAND = new DestructiveToolItem(new Item.Settings().maxCount(1), 18, 4, 20, "flame");
    public static final Item CATACLYSM_ROD = new DestructiveToolItem(new Item.Settings().maxCount(1), 28, 5, 30, "electric");
    public static final Item OBLIVION_SCEPTER = new DestructiveToolItem(new Item.Settings().maxCount(1), 48, 8, 50, "portal");
    public static final Item ANNIHILATION_STAFF = new DestructiveToolItem(new Item.Settings().maxCount(1), 55, 9, 60, "portal");

    public static void registerItems() {
        DestructiveMod.LOGGER.info("Registering items for " + DestructiveMod.MOD_ID);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "terra_crusher"), TERRA_CRUSHER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "magma_maul"), MAGMA_MAUL);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "void_hammer"), VOID_HAMMER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "thunder_smasher"), THUNDER_SMASHER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "frost_breaker"), FROST_BREAKER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "quake_hammer"), QUAKE_HAMMER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "meteor_maul"), METEOR_MAUL);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "abyss_crusher"), ABYSS_CRUSHER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "solar_smasher"), SOLAR_SMASHER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "chaos_hammer"), CHAOS_HAMMER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "ender_breaker"), ENDER_BREAKER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "titan_hammer"), TITAN_HAMMER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "core_drill"), CORE_DRILL);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "plasma_bore"), PLASMA_BORE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "seismic_drill"), SEISMIC_DRILL);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "magma_piercer"), MAGMA_PIERCER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "void_drill"), VOID_DRILL);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "quantum_bore"), QUANTUM_BORE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "tectonic_drill"), TECTONIC_DRILL);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "neutron_piercer"), NEUTRON_PIERCER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "nova_bomb"), NOVA_BOMB);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "antimatter_charge"), ANTIMATTER_CHARGE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "fusion_grenade"), FUSION_GRENADE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "dark_matter_mine"), DARK_MATTER_MINE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "plasma_cluster"), PLASMA_CLUSTER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "graviton_bomb"), GRAVITON_BOMB);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "singularity_charge"), SINGULARITY_CHARGE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "hypernova_mine"), HYPERNOVA_MINE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "photon_lance"), PHOTON_LANCE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "gamma_beam"), GAMMA_BEAM);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "plasma_cutter"), PLASMA_CUTTER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "neutron_ray"), NEUTRON_RAY);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "void_beam"), VOID_BEAM);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "solar_lance"), SOLAR_LANCE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "world_splitter"), WORLD_SPLITTER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "dimension_blade"), DIMENSION_BLADE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "reality_cleaver"), REALITY_CLEAVER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "void_edge"), VOID_EDGE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "chaos_saber"), CHAOS_SABER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "oblivion_katana"), OBLIVION_KATANA);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "entropy_blade"), ENTROPY_BLADE);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "annihilation_sword"), ANNIHILATION_SWORD);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "titan_fist"), TITAN_FIST);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "seismic_gauntlet"), SEISMIC_GAUNTLET);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "magma_claw"), MAGMA_CLAW);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "gravity_fist"), GRAVITY_FIST);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "void_grip"), VOID_GRIP);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "apocalypse_staff"), APOCALYPSE_STAFF);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "destruction_wand"), DESTRUCTION_WAND);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "cataclysm_rod"), CATACLYSM_ROD);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "oblivion_scepter"), OBLIVION_SCEPTER);
        Registry.register(Registries.ITEM, new Identifier(DestructiveMod.MOD_ID, "annihilation_staff"), ANNIHILATION_STAFF);
    }
}